#-----------------------------#
#   ArmorStandEditor-Reborn   #
#-----------------------------#

#DO NOT CHANGE THIS - CHANGES AUTOMATICALLY PER UPDATE
version: "1.19.2-37.2"

#----------- LANGUAGE
#Name of the language file you wish to use

#NOTE: If you are editing en_US.yml, it will not persist across restarts due to it being overwritten
#Please read the comments at the top of that file before editing/changing/modifying.
lang: en_US.yml

#----------- UPDATE NOTIFICATIONS
#Set this to allow your operators to get messages w.r.t Plugin updates
opUpdateNotification: false

#----------- TOOL SETTINGS

#Name of the edit tool's item Material. You can find a full list at https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
tool: FLINT

#(Optional) data that the plugin looks for to identify the edit tool, such as the damage value of a sword or the pattern of sandstone.
requireToolData: false
toolData: 0

#(Optional) The first "Lore" entry that the plugin looks for to identify the edit tool.
requireToolLore: false
toolLore: Let's get dangerous

#(Optional) Allow the use of CustomModelData - NOTE: This looks at the editTool set by Config
#and at the Int set here to know what to set.
#Also please if you are using this, ensure that you also give people the ability asedit.give in
#order to allow them to change their edit
#tool for the right Custom Model Data
allowCustomModelData: false
customModelDataInt: 0

#----------- ARMOR STAND SPECIFICS

#How many rotations to make a full circle in Coarse adjustment mode
coarse: 12

#How many rotations to make a full circle in Fine adjustment mode
fine: 120

#Allow the option to toggle invisibility for ItemFrames and ArmorStand
#YOu can either use this or the below permissions to allow visibility changes
#asedit.armorstand.invisible
armorStandVisibility: true
#asedit.itemframe.invisible
invisibleItemFrames: true


#------ GUI Options

#If true, the GUI will only open if the player is sneaking
requireSneaking: false

#------ Misc Options

#(Optional) Glowing Item Frames Support for Item Frames in 1.17 - WILL NOT WORK IN 1.16 OR LOWER AND 1.17.1 OR HIGHER
#If true, players can make itemFrames glow by right-clicking with a Glow Ink Sac
glowingItemFrame: true