#How many rotations to make a full circle in Coarse adjustment mode
coarse: 12

#How many rotations to make a full circle in Fine adjustment mode
fine: 120

#Name of the edit tool's item Material. You can find a full list at https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
tool: FLINT

#If true, the GUI will only open if the player is sneaking
requireSneaking: false

#Allow the option to toggle invisibility for ItemFrames and ArmorStand
ivisibleItemFrames: true
armorStandVisibility: true

#(Optional) data that the plugin looks for to identify the edit tool, such as the damage value of a sword or the pattern of sandstone.
requireToolData: false
toolData: 0

#(Optional) The first "Lore" entry that the plugin looks for to identify the edit tool.
requireToolLore: false
toolLore: Let's get dangerous

#Name of the language file you wish to use
lang: en_US.yml

#If false plugin notifications will be sent to the chat box. If true messages will be sent to the action bar.
sendMessagesToActionBar: true

#(Optional) Glowing Item Frames Support for Item Frames in 1.17 - WILL NOT WORK IN 1.16 OR LOWER AND 1.17.1 OR HIGHER
#If true, players can make itemFrames glow by right clicking with a Glow Ink Sac
glowingItemFrame: true

#DO NOT ENABLE - For Testing Purposes. Can lead to unwanted sideaffects
#Enable if you are submitting a bug report PLEASE!
debug: false