#-----------------------------#
#   ArmorStandEditor-Reborn   #
#-----------------------------#

#DO NOT CHANGE THIS - CHANGES AUTOMATICALLY PER UPDATE
version: "0.x-Rewrite"

#----------- LANGUAGE
#Name of the language file you wish to use

#NOTE: If you are editing en_US.yml, it will not persist across restarts due to it being overwritten
#Please read the comments at the top of that file before editing/changing/modifying.
lang: en_US.yml

#----------- WORLD SETTINGS
# Enable Per World Support for ArmorStandEditor - Not Enabling this
# means it will work for all worlds by default
enablePerWorldSupport: false

# Add in a list of Worlds where ArmorStandEditing is allowed to happen
# Please add your own worlds to this list. All Default Worlds are supported.
allowed-worlds:
  - world
  - world_nether
  - world_the_end

# ----- ArmorStand Specific Settings

#How many rotations to make a full circle in Coarse adjustment mode
coarse: 12

#How many rotations to make a full circle in Fine adjustment mode
fine: 120

# Set a server limit on the Size of an ArmorStand
minScaleValue: 0.1
maxScaleValue: 10

#Allow the option to toggle invisibility for ItemFrames and ArmorStand
#You can either use this or the below permissions to allow visibility changes
#asedit.togglearmorstandvisibility
armorStandVisibility: false
#asedit.toggleitemframevisibility
invisibleItemFrames: false

#----------- TOOL SETTINGS

#Name of the edit tool's item Material.
#You can find a full list at https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
tool: FLINT

#(Optional) data that the plugin looks for to identify the edit tool, such as the damage value of a sword or the pattern of sandstone.
requireToolData: false
toolData: 0

#(Optional) data that the plugin looks for to identify the name of the Edit Tool. Useful for Public Servers that do not want
#normal use of Flint to be impacted.
requireToolName: false
toolName: Example Name here

#(Optional) The first "Lore" entry that the plugin looks for to identify the edit tool. - Now has MultiLine Support
#NOTE: If you wish to make use of single line tool lore, please remove the 2nd item in the list and replace the first
#      text with what you want your ToolLore to be
requireToolLore: false
toolLore:
  - "TIME TO GET REALLY" #Replace if you want SingleLine ToolLore
  - "REALLY DANGEROUS!"  #Remove if you don't want MultiLine ToolLore


#------ GUI Options

#If true, the GUI will only open if the player is sneaking
requireSneaking: false

#Sends messages to the ActionBar
sendMessagesToActionBar: true


#------ Misc Options

#(Optional) Allow Players to get Player Heads from a Command. You can set this up either here or giving players
#asedit.head.
allowedToRetrieveOwnPlayerHead: false


# --- Development Flags:
# DO NOT USE IN PRODUCTION!
# WILL GENERATE ALOT OF NOISE!
# Will be TRUE while the rewrite is taking PLACE! YOU ARE WARNED!
debugFlag: true