name: ArmorStandEditor
main: io.github.rypofalem.armorstandeditor.ArmorStandEditorPlugin
version: 1.18-31
api-version: "1.13"
website: rypofalem.github.io
author: Wolfstorm
authors: [Wolfstorm, Marfjeh, rypofalem, sekwah41, Sikatsu1997, Cool_boy, sumdream, Amaury Carrade, nicuch, kotarobo, prettydude, Jumpy91, Niasio, Patbox, Puremin0rez, Prof-Bloodstone]
description: Allows players to edit data of armorstands without any commands.
softdepend: [Towny]
commands:
  ase:
    description: Changes the function of the armorstand edit tool.
    usage: /<command> ? - list subcommands
    permission: asedit.basic
permissions:
    asedit.basic:
      description: Allow use armorstand edit functions. If set to false it will override all other functions.
      default: true
    asedit.invisible:
      description: Toggles ArmorStand and ItemFrame visibility.
      default: true
    asedit.rename:
      description: Rename armorstands
      default: true
    asedit.equipment:
      description: Access armorstand equipment GUI
      default: true
    asedit.disableslots:
      description: Allows locking and unlocking the contents of an ArmorStand. When locked, armor and equipement can not be added or removed without unlocking it first.
      default: true