name: ArmorStandEditor
main: io.github.rypofalem.armorstandeditor.ArmorStandEditorPlugin
version: 1.20.0-43
api-version: "1.13"
folia-supported: true
website: https://www.spigotmc.org/resources/94503/
author: Wolfstorm
authors: [Wolfstorm, Pinnkk, Kugge, Marfjeh, miknes123, rypofalem, sekwah41, Sikatsu1997, Cool_boy, sumdream, Amaury Carrade, nicuch, kotarobo, prettydude, Jumpy91, Niasio, Patbox, Puremin0rez, Prof-Bloodstone, PlanetTeamSpeak]
description: Allows players to edit data of armorstands without any commands.
softdepend: [Towny, WorldGuard, GriefPrevention, PlotSquared, Lands, bentobox]

commands:
  ase:
    description: Changes the function of the armorstand edit tool.
    usage: /<command> ? - list subcommands
    aliases: [ase, asedit, armorstandeditor]
    permission: asedit.basic
    permission-message: "You are lacking the permission node 'asedit.basic'"

permissions:
  asedit.*:
    description: All ArmorStandEditor Commands
    default: op
    children:
      asedit.permpack.admin: true
      asedit.ignoreProtection.*: true

  asedit.basic:
    description: Allow use armorstand edit functions. If set to false it will override all other functions.
    default: true
  asedit.armorstand.invisible:
    description: Toggles ArmorStand visibility.
    default: false
  asedit.itemframe.invisible:
    description: Allows setting of ItemFrame Visibility
    default: false
  asedit.rename:
    description: Rename armorstands - Now Supports Color
    default: false
  asedit.equipment:
    description: Access armorstand equipment GUI
    default: false
  asedit.gravity:
    description: Changes whether the armor stand has gravity
    default: false
  asedit.placement:
    description: Changes whether the armor stand can be moved using the item for editing
    default: false
  asedit.disableSlots:
    description: Allows locking and unlocking the contents of an ArmorStand. When locked, armor and equipement can not be added or removed without unlocking it first.
    default: false
  asedit.give:
    description: Gives player the EditTool with Proper CustomModelData
    default: false
  asedit.update:
    description: Allows the checking for updates.
    default: false
  asedit.reload:
    description: Allows Reloading of the ASE Config.
    default: false
  asedit.toggleInvulnerability:
    description: Allows players to toggle the vulnerability state of an ArmorStand.
    default: false
  asedit.head:
    description: Allows players to trigger a command to retrieve a player head
    default: false


  asedit.ignoreProtection.towny:
    description: Allows user to ignore Towny's Protection Limitations.
    default: false
  asedit.ignoreProtection.griefProtection:
    description: Allows user to ignore GriefProtection's Protection Limitations.
    default: false
  asedit.ignoreProtection.plotSquared:
    description: Allows user to ignore PlotSquared's Protection Limitations.
    default: false
  asedit.ignoreProtection.worldGuard:
    description: Allows user to ignore WorldGuard's Protection Limitations.
    default: false
  asedit.ignoreProtection.skyblock:
    description: Allows user to ignore Skyblock's Protection Limitations.
    default: false
  asedit.ignoreProtection.griefDefender:
    description: Allows user to ignore GriefDefender's Protection Limitations.
    default: false
  asedit.ignoreProtection.lands:
    description: Allows user to ignore Lands Protection Limitations.
    default: false
  asedit.ignoreProtection.bentobox:
    description: Allows user to ignore Bentobox Protection Limitations.
    default: false
  asedit.ignoreProtection.residence:
    description: Allows user to ignore Residence Protection Limitations.
    default: false

  asedit.ignoreProtection.*:
    description: Ignore all Protection Limitations
    default: op
    children:
      asedit.ignoreProtection.towny: true
      asedit.ignoreProtection.griefProtection: true
      asedit.ignoreProtection.plotSquared: true
      asedit.ignoreProtection.worldGuard:  true
      asedit.ignoreProtection.skyblock: true
      asedit.ignoreProtection.griefDefender: true
      asedit.ignoreProtection.lands: true
      asedit.ignoreProtection.bentobox: true
      asedit.ignoreProtection.residence: true

  asedit.permpack.dontIgnoreProtections:
    default: true
    children:
      asedit.ignoreProtection.towny: false
      asedit.ignoreProtection.griefProtection: false
      asedit.ignoreProtection.plotSquared: false
      asedit.ignoreProtection.worldGuard:  false
      asedit.ignoreProtection.skyblock: false
      asedit.ignoreProtection.griefDefender: false
      asedit.ignoreProtection.lands: false
      asedit.ignoreProtection.bentobox: false
      asedit.ignoreProtection.residence: false

  asedit.permpack.basic:
    default: true
    children:
      asedit.basic: true
      asedit.equipment: true
      asedit.gravity: true
      asedit.placement: true
      asedit.disableSlots: true
      asedit.rename: true
      asedit.update: false
      asedit.give: false
      asedit.reload: false
      asedit.toggleInvulnerability: true
      asedit.head: false

  asedit.permpack.admin:
    default: op
    children:
      asedit.basic: true
      asedit.itemframe.invisible: true
      asedit.armorstand.invisible: true
      asedit.equipment: true
      asedit.gravity: true
      asedit.placement: true
      asedit.disableSlots: true
      asedit.rename: true
      asedit.update: true
      asedit.ignorePermissions.*: true
      asedit.reload: true
      asedit.toggleInvulnerability: true
      asedit.head: true
      asedit.give: true