name: ArmorStandEditor
version: '0.0.0.1'
main: io.rypofalem.armorstandeditor.ArmorStandEditorPlugin
api-version: '1.21'
load: STARTUP
author: Wolfstorm
authors: [Wolfstorm, DreiFxn, Pinnkk, Kugge, Marfjeh, miknes123, rypofalem, sekwah41, Sikatsu1997, Cool_boy, sumdream, Amaury Carrade, nicuch, kotarobo, prettydude, Jumpy91, Niasio, Patbox, Puremin0rez, Prof-Bloodstone, PlanetTeamSpeak]
description: Allows players to edit data of armorstands without any commands.
