name: ArmorStandEditor-APITester
main: main.java.io.github.rypofalem.apiexample.ArmorStandEditorAPITest
version: 1.20.0-43
api-version: "1.13"
website: https://www.spigotmc.org/resources/94503/
authors: [Wolfstorm, Kugge, Marfjeh, miknes123, rypofalem, sekwah41, Sikatsu1997, Cool_boy, sumdream, Amaury Carrade, nicuch, kotarobo, prettydude, Jumpy91, Niasio, Patbox, Puremin0rez, Prof-Bloodstone, PlanetTeamSpeak]
description: Allows players to edit data of armorstands without any commands.